<?php
    $projects = [];
    $projects[] = [
        'name'=>'husky',
        'display'=>'Husky Liners',
        'role'=>['Development','Interface','User Experience'],
        'type'=>'Website / Application',
        'description'=>'Worked closely with client and designers to rebrand, and launch new website and application. Built using PHP, on a custom in-house ERP and CMS. With close attention to analytics and A/B testing much of the interface and design was re-worked and optimized to further increase brand strength, leads, and sales. Client requested integration and optimization of many third party services including Bazaar Voice reviews.',
        'images'=>[
            [
                'src'=>'husky1.jpg',
                'text'=>'"Liners & Mats" product category page',
                'class'=>'screen'
            ],
            [
                'src'=>'husky2.jpg',
                'text'=>'Home page (tablet)',
                'class'=>'tablet'
            ],
            [
                'src'=>'husky3.jpg',
                'text'=>'All Products page',
                'class'=>'screen'
            ],
            [
                'src'=>'husky4.jpg',
                'text'=>'Product list (mobile)',
                'class'=>'mobile'
            ]
        ]
    ];
    $projects[] = [
        'name'=>'etools',
        'display'=>'Etool Developers',
        'role'=>['Development','Design','User Experience'],
        'type'=>'Website / Online Portfolio',
        'description'=>"At the request of the CEO and managers I took on a special project to rebrand and relaunch their outdated portfolio website. They requested something modern and mobile responsive which called attention to their trusted data-driven development and software, something which appealed to their automotive client base and their client's development needs.",
        'images'=>[
            [
                'src'=>'etools1.jpg',
                'text'=>'Home page',
                'class'=>'screen'
            ],
            [
                'src'=>'etools2.jpg',
                'text'=>'Contact page (tablet)',
                'class'=>'tablet'
            ],
            [
                'src'=>'etools3.jpg',
                'text'=>'Services page (mobile)',
                'class'=>'mobile'
            ]
        ]
    ];
    $projects[] = [
        'name'=>'century',
        'display'=>'Century',
        'role'=>['Development','User Experience'],
        'type'=>'Website',
        'description'=>"Worked with designers and client to rebrand and launch new website. Client was looking for something which appealed to their users, helped demonstrate the differences between their products, as well as guide users through the fitment process to generate leads. Site was built on custom in house ERP platform and integrated with the dealer communication system enabaling dealer network to view local leads generated by the site.",
        'images'=>[
            [
                'src'=>'century1.jpg',
                'text'=>'Home page',
                'class'=>'screen'
            ],
            [
                'src'=>'century2.jpg',
                'text'=>'Product page (tablet)',
                'class'=>'tablet'
            ],
            [
                'src'=>'century4.jpg',
                'text'=>'Product page',
                'class'=>'screen'
            ],
            [
                'src'=>'century3.jpg',
                'text'=>'Dealer locator (mobile)',
                'class'=>'mobile'
            ]
        ]
    ];
    $projects[] = [
        'name'=>'leer',
        'display'=>'LEER',
        'role'=>['Development','Interface','User Experience'],
        'type'=>'Website / Application',
        'description'=>"Worked closely with designers and client to rebrand and launch new website and application. The interface is designed to help the user navigate data-intensive fitments to easily find a suitable product for their vehicle. Lead generation and analytics were an important factor in this project. Site integrated closely with dealer communication system. Worked with marketing manager to integrate dealer reward program, and custom order forms used by dealers.",
        'images'=>[
            [
                'src'=>'leer1.jpg',
                'text'=>'Home page',
                'class'=>'screen'
            ],
            [
                'src'=>'leer2.jpg',
                'text'=>'Product list',
                'class'=>'screen'
            ],
            [
                'src'=>'leer3.jpg',
                'text'=>'Dealer locator (tablet)',
                'class'=>'tablet'
            ],
            [
                'src'=>'leer4.jpg',
                'text'=>'Video page (tablet)',
                'class'=>'tablet'
            ]
        ]
    ];
    $projects[] = [
        'name'=>'evercoat',
        'display'=>'Evercoat',
        'role'=>['Development'],
        'type'=>'Website',
        'description'=>"Worked as full-stack developer on launch of international site, representing many products across many locations. The focus of this project was multilingual capabilites with unique product groups for each location. Interface designed to demonstrate product range and work as a global dealer locator for site visitors.",
        'images'=>[
            [
                'src'=>'evercoat1.jpg',
                'text'=>'About page (tablet)',
                'class'=>'tablet'
            ],
            [
                'src'=>'evercoat2.jpg',
                'text'=>'Home page (mobile)',
                'class'=>'mobile'
            ],
            [
                'src'=>'evercoat3.jpg',
                'text'=>'Language selector',
                'class'=>'screen'
            ]
        ]
    ];
    $projects[] = [
        'name'=>'livernois',
        'display'=>'Livernois',
        'role'=>['Development','Design','User Experience'],
        'type'=>'Website / Application',
        'description'=>"Worked closely with client as lead designer and full-stack developer to rebrand and relaunch their ecommerce website. Client wanted something fully responsive, which appealed to their users and worked closely with Fedex API.",
        'images'=>[
            [
                'src'=>'livernois1.jpg',
                'text'=>'Shop category page',
                'class'=>'screen'
            ],
            [
                'src'=>'livernois2.jpg',
                'text'=>'Mobile menu',
                'class'=>'mobile'
            ],
            [
                'src'=>'livernois3.jpg',
                'text'=>'Product page (tablet)',
                'class'=>'tablet'
            ]
        ]
    ];
    $projects[] = [
        'name'=>'designcraft',
        'display'=>'Designcraft',
        'role'=>['Development','Design'],
        'type'=>'Website',
        'description'=>"Worked closely with client to design and develop new site to represent brand. The client requested something that demonstrated the craftsmanship and professionalism of his products and services.",
        'images'=>[
            [
                'src'=>'designcraft1.jpg',
                'text'=>'Home page',
                'class'=>'screen'
            ]
        ]
    ];
    $projects[] = [
        'name'=>'aacf',
        'display'=>'AACF',
        'role'=>['Front-end','User Experience'],
        'type'=>'Website',
        'description'=>"Worked closely with charity and design firm, on tight schedule, to brand and launch new website. Client requested something that represented their mission, donors, and was capable of accepting donations.",
        'images'=>[
            [
                'src'=>'aacf2.jpg',
                'text'=>'Home page (tablet)',
                'class'=>'tablet'
            ],
            [
                'src'=>'aacf3.jpg',
                'text'=>'Contact form',
                'class'=>'screen'
            ],
            [
                'src'=>'aacf1.jpg',
                'text'=>'Mobile menu',
                'class'=>'mobile'
            ],
            [
                'src'=>'aacf5.jpg',
                'text'=>'About page',
                'class'=>'screen'
            ]
        ]
    ];
    $projects[] = [
        'name'=>'pace',
        'display'=>'Pace Edwards',
        'role'=>['Front-end','User Experience'],
        'type'=>'Website',
        'description'=>"Worked with client and designers to launch new website alongside new branding. Integrated with ERP platform, creating dealer locator which shows customer appropriate dealer for their location.",
        'images'=>[
            [
                'src'=>'pace1.jpg',
                'text'=>'Home page',
                'class'=>'screen'
            ],
            [
                'src'=>'pace2.jpg',
                'text'=>'International dealers (tablet)',
                'class'=>'tablet'
            ],
            [
                'src'=>'pace3.jpg',
                'text'=>'Product page (tablet)',
                'class'=>'tablet'
            ]
        ]
    ];
    $projects[] = [
        'name'=>'cmu',
        'display'=>'CMU',
        'role'=>['Front-end','User Experience'],
        'type'=>'Website / Application',
        'description'=>"Worked with team assigned to building and relaunching new website based on third party designs. Built new interface that worked with existing asp.net application. Worked closely with team assigned to application process and university maps.",
        'images'=>[
            [
                'src'=>'cmu2.jpg',
                'text'=>'Application page',
                'class'=>'screen'
            ],
            [
                'src'=>'cmu1.jpg',
                'text'=>'Map page (mobile)',
                'class'=>'mobile'
            ]
        ]
    ];